with source as (

    select * from {{ source('ocn_sources', 'db_stock_vehicles_status_histories') }}

),

renamed as (

    select
        business_date,
        contract_number,
        vin,
        dpd,
        last_payment_received_date,
        contract,
        history_id,
        step,
        time,
        user_id,
        description,
        schema_version,
        stock_vehicles_id,
        adendum_service_count,
        agency_payment_date,
        bill,
        bill_amount,
        bill_date,
        bill_number,
        brand,
        can_finish_process,
        car_number,
        category,
        color,
        country,
        created_at,
        delivered_date,
        delivery_confirmation,
        extension_car_number,
        gps_installed,
        gps_number,
        gps_serie,
        is_blocked,
        is_electric,
        km,
        maintenance_history,
        mi,
        model,
        motor_number,
        new_car,
        owner,
        payment_count,
        physical_status,
        platform,
        qr_code,
        readmission_date,
        readmission_reason,
        ready_to_deliver,
        reception_date,
        state,
        status,
        sub_category,
        transferred_to,
        updated_at,
        vehicle_docs_complete,
        vehicle_physically_received,
        vehicle_state,
        version,
        vin_number_validated,
        year,
        last_driver_index,
        last_driver_id,
        stock_vehicle_status_histories_id,
        associate_id,
        canceled_at,
        commments,
        date_in,
        date_out,
        is_canceled,
        is_completed,
        previous_category,
        previous_status,
        previous_step,
        previous_sub_category,
        stockid,
        userid

    from source

)

select * from renamed